### ISSUE TITLE
Engage: quote should mention who we're qouting in 

### ISSUE THREAD

**Issue by csmart** [kororaproject/website#11]
When quoting someone's post in Engage it would be handy to have it say who we're quoting and from when. I.e., at the top of the post add:

> csmart wrote at 2013-01-11 10:35:
> I love Korora!

Then it's easy to know who we're replying to, and useful for when you quote two people in one reply.

**Comment by firnsy** [comment]
fixed in bfce4869d3fb286ee69bce895db0c5cde8338dd3
