### ISSUE TITLE
Engage: link to posts

### ISSUE THREAD

**Issue by csmart** [kororaproject/website#13]
It would be great to be able to link to any post in an engage thread so that we can help others by directing them right to an answer.

**Comment by firnsy** [comment]
Are you referring to easy access to this link (like right click copy shortcut) or something else?

**Comment by csmart** [comment]
Yeah, or drop down the config cog and "link to post" which browses direct to the post, then we can manually copy the link from browser URL?

**Comment by firnsy** [comment]
ok i'm on the same page then
