### ISSUE TITLE
Engage: some funny chars

### ISSUE THREAD

**Issue by csmart** [kororaproject/website#14]
Some chars aren't showing properly, probably some European chars or something?

https://kororaproject.org/support/engage/problem/gnome-spin-dont-boot?page=2

> whatÃÂ´s wrong with the iso? DonÃÂ´t have EFI, other ditsris in livemode show grubmenu Looks like it's not being written properly or something. Which other Linux distros have you tried that booted from USB successfully?

**Comment by firnsy** [comment]
yes this is damn utf8 enconding issues
