### ISSUE TITLE
Answer after quote disappears

### ISSUE THREAD

**Issue by jimkp** [kororaproject/website#18]
If a blank line isn't inserted after a quote the answer isn't visible. It is still there as it can be viewed on the edit screen but doesn't appear on the thread.
Inserting a blank line makes it appear.

**Comment by firnsy** [comment]
@jimkp can you post provide a link to a thread that this occurs in so I can reproduce please

**Comment by jimkp** [comment]
Look at my last reply in https://kororaproject.org/support/engage/idea/k20gnome-wallpaper (i edited to duplicate the lines, only one can be seen except on the edit screen)

**Comment by firnsy** [comment]
thanks @jimkp, that's exactly what i was looking for. i was reproducing incorrectly.

**Comment by jimkp** [comment]
I probably didn't describe it very well but pleased you can see it now.

**Comment by firnsy** [comment]
ok, so thinking about this, i'm not entirely convinced it's a bug, i think clarification of the syntax is warranted.

**Comment by jimkp** [comment]
I'm not sure this is solved as problems still occur. I noticed today that
someone answer appeared in the quote,
https://kororaproject.org/support/engage/question/is-it-possible-to-move-the-top-bar

On 13 January 2014 21:08, Ian Firns notifications@github.com wrote:

> Closed #18 https://github.com/kororaproject/kp-canvas/issues/18 via
> 956ce30https://github.com/kororaproject/kp-canvas/commit/956ce3098c3366953d2bcdb2c432898c113c89fa
> .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/kororaproject/kp-canvas/issues/18
> .

## 

Jim Dean

Email - jdean55@gmail.com

On Google+ https://plus.google.com/+JimDean
My YouTube Channel http://www.youtube.com/user/nkpnsw?feature=mhum
My tech blog "Techodyssey" http://ozjd.wordpress.com/
