### ISSUE TITLE
Stay Logged In

### ISSUE THREAD

**Issue by jimkp** [kororaproject/website#27]
I find I need to log back in often several times a day. E.g. if I suspend when I return even an hour or 2 later I need to log in again especially if I have logged in on a mobile device  during the break.
Also if I log out of the desktop and straight back in I need to log in to Engage again.

**Comment by firnsy** [comment]
fixed

**Comment by jimkp** [comment]
Still need to log in here especially if I switch devices. E.g. am logged in on the desktop, shutdown, log in on laptop then later shut it down and come back to desktop I need to log in again.
