### ISSUE TITLE
For code, include line numbers

### ISSUE THREAD

**Issue by csmart** [kororaproject/website#28]
To prevent issues on small screens where a single command inside a code tag wraps and looks like two separate commands, could we use something like line numbers to show that it's only one command, but when the user highlights it only copies the command?

Something like:
1. sudo /usr/sbin/alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 20000
2. sudo /usr/sbin/alternatives --config javac

**Comment by dyoungwd** [comment]
Basically all is required is to add an ordered list tags between the pre and code tags, changing the html to

&lt;pre>
     &lt;ol>
         &lt;li>&lt;code class="language-bash"> sudo /usr/sbin/alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 20000 &lt;/code>&lt;/li>

   &lt;li>&lt;code class="language-bash"> sudo /usr/sbin/alternatives --config javac&lt;/code>&lt;/li>
     &lt;/ol>
&lt;/pre>

`<pre>
     <ol>
         <li><code class="language-bash"> sudo /usr/sbin/alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 20000 </code></li>

   <li><code class="language-bash"> sudo /usr/sbin/alternatives --config javac</code></li>
     </ol>
</pre>`
