### ISSUE TITLE
Add Markdown link

### ISSUE THREAD

**Issue by jimkp** [kororaproject/website#29]
As suggested in https://kororaproject.org/support/engage/idea/please-put-a-link-directly-to-engage-markdown-on-the-top-engage-page add a link to the markdown screen on the engage page. Also on the edit screen.

**Comment by firnsy** [comment]
fixed in 3aa7f97893865a73cdc5f037230994c7cabe2c9b

**Comment by jimkp** [comment]
Thanks for quick fix.
Still would be nice to have it on the edit screen too.

**Comment by firnsy** [comment]
@jimkp, it is on the edit screen for the original item.

it is on the edit screen for replies too in my local repo, but is not pushed up, though will be during lunch.

**Comment by jimkp** [comment]
Thanks
