### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by jamespeek** [kororaproject/website#7]
Few low-hanging fixes to the HTML should fix up the validation; removing /img and /input tags and adding alt text to the images should sort out the majority. Worth doing since Google is thought to give better ranking in results to valid markup. Wouldn't worry about the CSS unless there are things that are breaking it in other browsers; search engines don't care about CSS.

**Comment by jamespeek** [comment]
We are down to one now; the ng-app on the html tag. We might be able to change that to a data-ng-app to validate (I think angular still works when it is that; @firnsy wanna check?

**Comment by firnsy** [comment]
title page down to 2 warnings, closing for now
